name: Build and Deploy Android App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  androidAPK:
    name: Build CI (Android)
    runs-on: ubuntu-latest
    environment: Production

    # envirenment: production
    # env:
    #   ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
    #   IOS_FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
    #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - name: "Create env file"
        run: |
          touch env
          echo API_BASE_URL=${{ vars.API_BASE_URL }} >> env
          cat env

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.9" # Use the latest stable version or specify the version you need
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # - name: Run build_runner (command)
      #   run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release Save Build at Github
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
